#!/usr/bin/env python3
"""E012 decision rule as a program + report tables.

    nix develop .#gate1 -c python backtest_model_server/e012/tables12.py

Applies loop/experiments/E012-vol-gate-capture.md's pre-registered clauses
to out/final_results.json — nothing else. Output: out/decision.json,
out/tables.md.
"""

from __future__ import annotations

import common12 as C12

FIN = C12.OUT / "final_results.json"


def main() -> int:
    fin = C12.read_json(FIN)
    checks = C12.read_json(C12.OUT / "checks_results.json")
    tr = C12.read_json(C12.OUT / "tune_results.json")
    frozen = C12.read_json(C12.OUT / "params_frozen.json")
    tune_by = {f"{c['candidate']}|{c['arm']}": c["tune"]
               for c in frozen["cells"]}
    target = C12.TARGET_10PCT
    base = fin["baselines"]
    best_static = max(b["central"]["per_day_usd"] for b in base.values())
    bar = max(0.915, best_static)

    supported, rows = [], []
    for key, c in sorted(fin["cells"].items()):
        lab = c["arm"]
        full = c["points"]["central"]["per_day_usd"]
        aug = c["points"]["central"]["august_net_usd"]
        ai_full = base[lab]["central"]["per_day_usd"]
        ai_aug = base[lab]["central"]["august_net_usd"]
        ok = (full >= target and aug > 0.0
              and full > ai_full and aug > ai_aug)
        if ok:
            supported.append(key)
        rows.append({
            "cell": key, "cfg": c["cfg"],
            "tune_per_day": tune_by[key]["per_day_usd"],
            "full_per_day": {pn: c["points"][pn]["per_day_usd"]
                             for pn in C12.POINTS},
            "august_net": {pn: c["points"][pn]["august_net_usd"]
                           for pn in C12.POINTS},
            "held_frac": c["held_frac_mask"],
            "n_streaks": c["n_streaks"],
            "beats_same_arm_always_in_full": full > ai_full,
            "beats_same_arm_always_in_august": aug > ai_aug,
            "meets_target": full >= target,
            "august_positive": aug > 0.0,
        })

    best_cell = max(rows, key=lambda r: r["full_per_day"]["central"])
    clause1_fires = best_cell["full_per_day"]["central"] <= bar
    clearing = [r for r in rows if r["meets_target"]]
    clause2_vacuous = not clearing
    clause2_fires = bool(clearing) and all(
        not r["august_positive"] for r in clearing)

    if supported:
        verdict = "SUPPORTED"
    elif clause1_fires or clause2_fires:
        verdict = "REFUTED"
    else:
        verdict = "INCONCLUSIVE"

    decision = {
        "experiment": "E012",
        "verdict": verdict,
        "target_per_day_usd": target,
        "refuted_bar_per_day_usd": bar,
        "best_static_arm_per_day_usd": best_static,
        "supported_cells": supported,
        "refuted_clause_1_no_gate_beats_wide_static": clause1_fires,
        "refuted_clause_2_all_qualifiers_fail_august": clause2_fires,
        "refuted_clause_2_vacuous": clause2_vacuous,
        "best_cell": {"cell": best_cell["cell"],
                      "full_per_day_central":
                          best_cell["full_per_day"]["central"]},
        "tune_framing": checks["tune_baseline"],
        "cells": rows,
    }
    C12.write_json(C12.OUT / "decision.json", decision)

    lines = ["# E012 tables (generated by tables12.py)", "",
             f"**Verdict: {verdict}** — best cell "
             f"{best_cell['cell']} ${best_cell['full_per_day']['central']:+.3f}/day "
             f"central vs bar ${bar:+.3f}/day "
             f"(target ${target:+.4f}/day).", "",
             "| cell | cfg | tune $/d | full o/c/p $/d | Aug c $ | held % "
             "| streaks | beats own always-in (full/Aug) |",
             "|---|---|---:|---|---:|---:|---:|---|"]
    for r in rows:
        f = r["full_per_day"]
        lines.append(
            f"| {r['cell']} | `{r['cfg']}` | {r['tune_per_day']:+.3f} "
            f"| {f['optimistic']:+.2f} / **{f['central']:+.2f}** / "
            f"{f['pessimistic']:+.2f} "
            f"| {r['august_net']['central']:+.1f} "
            f"| {r['held_frac']*100:.1f} | {r['n_streaks']} "
            f"| {'Y' if r['beats_same_arm_always_in_full'] else 'N'}/"
            f"{'Y' if r['beats_same_arm_always_in_august'] else 'N'} |")
    lines += ["", "| baseline | full o/c/p $/d | Aug c $ |", "|---|---|---:|"]
    for lab, b in base.items():
        lines.append(
            f"| always-in {lab} | {b['optimistic']['per_day_usd']:+.2f} / "
            f"**{b['central']['per_day_usd']:+.2f}** / "
            f"{b['pessimistic']['per_day_usd']:+.2f} "
            f"| {b['central']['august_net_usd']:+.1f} |")
    tb = checks["tune_baseline"]
    lines += ["",
              f"Tune framing: {tb['cells_positive_in_tune']}/{tb['n_cells']} "
              f"cells positive in tune, but "
              f"{tb['cells_beating_same_arm_always_in']} beat same-arm "
              f"always-in in tune (always-in tune: "
              + ", ".join(f"{k} ${v['per_day_usd']:+.3f}/d"
                          for k, v in tb['always_in_tune'].items())
              + ")."]
    (C12.OUT / "tables.md").write_text("\n".join(lines) + "\n")
    print("\n".join(lines[:8]))
    print(f"wrote {C12.OUT/'decision.json'} and tables.md")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
